### PR TITLE
Improved and refactored whole Project Structure

### LINKED ISSUE #326: improve package structure
**Describe the bug**
classes are not managed properly. gui contains some core classes. whereas almost all the files are stored in main. Why?, even utils are stored in main. Its difficult to find activities.
One activity lies in a completely different package, program-modes. This will result in the code being not maintainable. 
Screenshot 2019-06-25 at 11 58 06 AM

**Would you like to work on the issue?**
@jddeep @suresh-gandhi take care of it

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #326 
**Changes**: Refactored whole Project Structure.

**Screenshot/s for the changes**: 
> Not available

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
>  Not available

### CODE REVIEW

**Comment by jddeep** [comment]
Merging #335 and #338 will be beneficial before this. Fixing travis builds will become feasible then. Also otherwise this will seem to have some similar changes.

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
1. There's a rocket image in the root folder.
2. Also I noticed in some places `{` is in a new line, not next to method declaration line. 
3. Remove redundant classes. (Eg: Serial communication classes from desktop app etc.)
Look for them and correct.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please resolve Travis failing.

**Comment by jddeep** [comment]
@mariobehling @CloudyPadmal Could you please review and merge this. Thanks.

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
