### PR TITLE
Adding Datasets for EEG testing

### LINKED ISSUE #288: Datasets for EEG testing
**Describe the issue**

We need more data to implement features. Best way for now is to look for free and open datasets recorded by researchers and use it in our app. Repository https://github.com/meagmohit/EEG-Datasets contains a set of public data sets.

This issue is to pick the appropriate ones related to EEG and prepare those data sets to feed into NeuroLab through Arduino interface

Task: Pick 10 different data sets from the above mentioned repository and pre-process them to match with our hardware interface

**Would you like to work on the issue?**

Issue for GSoC
@jddeep and @suresh-gandhi please pick 5 each and list the headings under this issue (to avoid duplicates). After that, create a folder in repo root and add pre-processed data. Set priority to recognized datasets. (eg: MNIST, OpenBCI etc...). Limit the pre-processed data set to be under 25MB. Format would be the same as the sample dataset we have in repo.

| time | data | data (if available) |
| ----- | ------ | ------ | 
| ttttt | 4526.24544 ... | 4952.11555 ... |
| ttttt | 4526.24544 ... | 4952.11555 ... |
| ... | ... | ... |
| ttttt | 4526.24544 ... | 4952.11555 ... |

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #288 

**Changes**: Adding Datasets for EEG testing.

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
> Not available

### CODE REVIEW

**Comment by jddeep** [comment]
@CloudyPadmal There seems to be some problem with the MNIST and Imagenet-brain websites as the datasets just won't download. Have been trying for quite a while. There could also be an internet problem, hence will try again in morning time. But have added others from which I mentioned here #288. Please review and tell me if this PR format is all right or anything needs to be changed. Thanks.

**Review by suresh-gandhi — CHANGES_REQUESTED** [review]
@jddeep It would be better if you add a brief description (at least the CSV table format; axes labels; data size; subject demographics etc) along with relevant plots of the datasets involved in each directory. Would make it easier for us to program in the long run (while writing the Android Code for these datasets).

**Comment by jddeep** [comment]
@CloudyPadmal should I add the table format/field labels in the CSV file itself (like in the first line) or make another file (containing only the format and field labels) for those of each dataset?

**Comment by CloudyPadmal** [comment]
@jddeep datasets are ok. Just add a header to each csv with a label which we can later use to parse the file. If you can put the original labels relevant to each column, that's more preferable

**Comment by jddeep** [comment]
@CloudyPadmal Done.

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
