### PR TITLE
feat: normalized datasets

### LINKED ISSUE #304: Normalize the datasets
**Describe the issue**

In the set of current datasets added, there are variations in different datasets. We need to normalize all of them to a common basis.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes #304 

**Changes**: 
- Removed outliers from datasets and normalized them to have common levels.
- One dataset per one directory

**Screenshot/s for the changes**: 
> Not available

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [X] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [X] My code does not contain any extra lines or extra spaces
- [X] I have requested reviews from other members

**APK for testing**:
> Not available

### CODE REVIEW

**Review by jddeep — APPROVED** [review]
Jeez! That's a hell lot of changed files xD

**Comment by CloudyPadmal** [comment]
Yea did a full clean up to datasets. Now they all share a common format and similar range. Makes it easier to process.

**Comment by jddeep** [comment]
> Yea did a full clean up to datasets. Now they all share a common format and similar range. Makes it easier to process.

Cool :+1:

**Comment by CloudyPadmal** [comment]
I've missed numbering for dataset6 and made dataset35 as dataset6

**Comment by jddeep** [comment]
> I've missed numbering for dataset6 and made dataset35 as dataset6

Okay. So did you directed them in this commit?

**Comment by CloudyPadmal** [comment]
Yep it's now updated.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
