### PR TITLE
Implemented Focus Main Screen

### LINKED ISSUE #350: Focus Mode Main Screen with Instructions and games.
**Actual Behaviour.**  
Missing Focus Mode Main Screen with Instructions and games.

**Expected Behaviour**  
Focus Mode Main Screen with Instructions and games.

**Steps to reproduce it**  
> Not available

**Additional context**  
> Not available

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #350 
**Changes**: Implemented Focus Main Screen
**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/neurolab-android/files/3386224/app-debug.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Why a green color?

**Comment by jddeep** [comment]
> Why a green color?

The current defined Accent color didn't contrast much. Do you suggest we use the primary purple-ish color?

**Comment by CloudyPadmal** [comment]
Yes purple is good. Follow material design color palate.

**Comment by adityastic** [comment]
The Background xD

**Comment by CloudyPadmal** [comment]
Background looks stretched :thinking:

**Comment by jddeep** [comment]
Yeah, the background can be changed, i used the card background with a different tint here.

**Comment by adityastic** [comment]
Want a Background xD ?

**Comment by jddeep** [comment]
@adityastic sure, just make one looking at the content and make it spaced out so that it can be used as the background xD

**Comment by CloudyPadmal** [comment]
@jddeep also mind the font sizes. Follow material design guidelines. They are for this exact reason.

**Comment by jddeep** [comment]
@CloudyPadmal Have made updates (Check the PR body ss). We can progress from here. Please review and do tell me if something more needs to be added here.

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
