### PR TITLE
chore : Add contributing.md file link in readme file.

### LINKED ISSUE #521: Add Contributing.md link in Readme.md
**Describe the issue**

Contributing.md link should be present in the Readme file. 
It will assist newcomers to setup project as Readme.md is a place to read
instructions about setting up project and start contributing.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by dipu989**
Fixes #521 

**Changes**:
Added project setup instructions link in Readme.md file.

**Screenshot/s for the changes**: 
NA

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
NA

### CODE REVIEW

**Comment by dipu989** [comment]
@jddeep @adityastic Please review this!

**Review by adityastic — APPROVED** [review]
Looks good, instead of docs, you can use chore

**Comment by dipu989** [comment]
> Looks good, instead of docs, you can use chore

Changed it! Will keep this in mind from the next time :+1:

**Review by jddeep — APPROVED** [review]

**Comment by mariobehling** [comment]
Reverting this as contributing.md was deleted. Standard setup procedures for Android apps are already documented elsewhere.

**Pull request merged**
