### PR TITLE
Density Spectrum Graph in Memory Graph

### LINKED ISSUE #310: Parse receiving neuro data and display frequency spectrum
**Describe the issue**

Similar to muze, display the frequency spectrum of the receiving data stream. Functions required to do the calculations are already available on desktop app which was ported. Please look up to implementation in desktop app and the following UI to output the frequency spectrum. I would suggest to have a better understanding about what is a frequency spectrum is before you start so that we'll have a better result.

spectrum

This view can be placed in Memorygraph activity

**Would you like to work on the issue?**

Issue for GSoC

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #310 

**Changes**: Density Spectrum Graph in Memory Graph.

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Actually this is not how a spectrum looks like. https://www.scichart.com/android-chart-features/?source=MPAndroidChart see **Extreme Realtime Performance** section. But such a feature is not available for free in MPAndroidChart it seems. But there's a way https://stackoverflow.com/questions/25541964/draw-spectrogram-graph-of-audio-file-in-android. Let's see

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please:

* Also ensure you include numbers and units on both x and y axis
* Avoid small issues like no space in front a bracket: It is "Frequency (Hertz)" not "Frequency(in hertz)
* There is no point in requiring the user to click too often. Why do you need a pop up for just a little bit of info. Design a screen that includes such info, if the text is not too long.

**Comment by jddeep** [comment]
@mariobehling Thanks for the feedback. Just the initial UI. Will update and enable the X units. Will keep in mind about the small issues mentioned.

**Comment by jddeep** [comment]
Made the changes. @CloudyPadmal We can merge this as WIP and progress untill the FFT algo is up and running correctly. @mariobehling Please check the screenshot now for the UI. Do tell me if anything more needs to be changed. I am thinking of a different contrasting color for background.

**Review by mariobehling — APPROVED** [review]

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
