### PR TITLE
Improved the UI by making consistent color scheme throughout and other fixes

### LINKED ISSUE #262: Inconsistant color theme
**Describe the bug**
There is a color mismatch between windows. Main window has a orange color theme and the inner windows are all grayish. 

**Expected Behavior**
We need to have a consistent color palate in all places. Either gray or orange; one.

**Steps to reproduce it**
Observe different screens and their colors

**LogCat for the issue**
> Not available

**Screenshots of the issue**

| Main window (Orange) | Inner windows (Gray) |
| ---------------- | ------------------- |
|||

|               | |
|---------------|-|
|Device         |  Pixel |
|Android Version| Oreo 27 |

**Would you like to work on the issue?**
GSoC Issue

### PR DESCRIPTION
**Pull request by suresh-gandhi**
Fixes #262.

**Changes**: 
* Made the color scheme consistent throughout and did some other minor fixes for UI improvement.

**Screenshot/s for the changes**: 
<table>
<tr>
<td></td>
<td></td>
<td>
</td>
</tr>
</table>

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**Apk for testing:**
[app-debug.zip](https://github.com/fossasia/neurolab-android/files/3235705/app-debug.zip)

### CODE REVIEW

**Comment by suresh-gandhi** [comment]
Requesting peer review @adityastic @jddeep @ho-dor @CoderVishalSehgal.

**Review by jddeep — COMMENTED** [review]
@suresh-gandhi Please check once in the Settings, if the app crashes on entering any text AND check if only numeric keyboard pops while setting the values. If not please make the necessary changes.

**Comment by CloudyPadmal** [comment]
@suresh-gandhi please provide APK to test always

**Comment by suresh-gandhi** [comment]
@CloudyPadmal Ahh... Missed that. I would take care from next time. Thanks. Added and resolved the merge conflicts.

**Comment by suresh-gandhi** [comment]
@jddeep The app doesn't crash and the numeric keyboard works well. You can test the apk for reference. Thanks for your review.

**Review by CloudyPadmal — APPROVED** [review]

**Review by jddeep — APPROVED** [review]

**Pull request merged**
