### PR TITLE
Fixed Dimens and Redundant Res

### LINKED ISSUE #453: Remove duplicate resources and dimens values
**Describe the bug**
Some resource files are redundant in the app codebase and not needed. 
Also, there are duplicate dimens values. Remove them and be sure to make changes wherever the duplicates were used throughout the codebase.

**Expected Behavior**
Remove duplicate resources and dimens values

**Steps to reproduce it**
Go through the resources and codebase of the app.

**Would you like to work on the issue?**
Issue for Codeheat.

### PR DESCRIPTION
**Pull request by CodeMonk263**
Fixes #453 

**Changes**: Fixed Dimens redundant values and unused resources

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Review by CloudyPadmal — COMMENTED** [review]
Is this from code inspection?

**Comment by CodeMonk263** [comment]
> Is this from code inspection?

I used android lint and made sure that the build didn't fail. Is that not the way to go?

**Comment by CodeMonk263** [comment]
Can someone pls review this and guide me as to what to do.

**Review by jddeep — APPROVED** [review]

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
I'm not sure if we really need this PR. App hasn't been tested with real hardware and removing all the core components even though they were not used for now will surely make further development harder. Let's keep those as it doesn't hurt any performance.

Also not that for string and style resources, so called unused ones were just commented. Remove only those resources but not code parts.

**Comment by jddeep** [comment]
We can open this later if we require. Thanks.

**Pull request closed without merging**
