### PR TITLE
Removed the fab

### LINKED ISSUE #29: The Snackbar FAB is not needed.
**Actual Behaviour** The unnecessary FAB.

Please state here what is currently happening.

**Expected Behaviour** Clean background.

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**
Yes, I am working on that issue.

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #29 

**Changes**: Removed the FAB.

**Screenshot/s for the changes**: [Add screenshot/s of the layout where you made changes or a `*.gif` containing a demonstration]

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Comment by jddeep** [comment]
@CloudyPadmal I am extremely sorry. It was a silly mistake from my side only, I made the changes in ` MainActivty.java ` on the development branch and that is why builds were failing for PR's from this branch. Now as you can see it has successful Travis builds. Now you can review it. Thanks.

**Comment by CloudyPadmal** [comment]
Why #30 is closed? All that review is in vain. Please update the branch you are working with upstream/development. This PR still has changes related to #28

**Comment by jddeep** [comment]
> Why #30 is closed? All that review is in vain. Please update the branch you are working with upstream/development. This PR still has changes related to #28

@CloudyPadmal sir, I tried reopening #30  before making #31 but it was not to be due to the Reopen button was dysfunctional there.

**Comment by jddeep** [comment]
@CloudyPadmal and yeah #31 was made after #28 so it has changes related to the later.

**Comment by jddeep** [comment]
> > Why #30 is closed? All that review is in vain. Please update the branch you are working with upstream/development. This PR still has changes related to #28
> 
> @CloudyPadmal sir, I tried reopening #30 before making #31 but it was not to be due to the Reopen button was dysfunctional there.

Sir, what do you suggest that can be done at this stage? Should I close this #31  and try reopening #30 ? Or there is some other way?

**Comment by CloudyPadmal** [comment]
I suggest you get some practice with git version controlling first and how to work with different branches.

**Comment by jddeep** [comment]
> I suggest you get some practice with git version controlling first and how to work with different branches.

@CloudyPadmal Sure. Thanks

**Pull request closed without merging**
