### PR TITLE
Improved UI of bluetooth test

### LINKED ISSUE #489: Improve UI of Bluetooth test in developer mode
**Actual Behaviour.**  

The UI of bluetooth test is very rudimentary.

**Expected Behaviour**  

A good UI should be there.

**Steps to reproduce it**  

In developer mode, open bluetooth test.

**Additional context**  
Screenshot_20191002-153328_NeuroLab

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #489 

**Changes**: UI of bluetooth test screen improved.

**Screenshot/s for the changes**:
Screenshot_20191002-154952_NeuroLab

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by jddeep** [comment]
@adityastic What is the problem with these travis builds here :thinking: ?

**Comment by ho-dor** [comment]
any idea @adityastic ?

**Comment by adityastic** [comment]
@ho-dor @jddeep sorry, I missed the message. Let me check the issue

**Comment by jddeep** [comment]
@ho-dor Please pull latest changes and rerun the build here. Thanks.

**Comment by ho-dor** [comment]
@jddeep updated

**Review by adityastic — APPROVED** [review]

**Comment by adityastic** [comment]
@jddeep rtm

**Review by jddeep — APPROVED** [review]

**Pull request merged**
