### PR TITLE
Fixed the Incorrect package name of NeuroUtils class

### LINKED ISSUE #98: Incorrect package name of NeuroUtils class
**Actual Behaviour**

Currently, NeuroUtils is in org.neurovillage.main package which is incorrect. (I guess it was a minor error in porting as the package name corresponds to neurolab-desktop not neurolab-android)

**Expected Behaviour**

NeuroUtils should be included in io.neurolab package.

**Would you like to work on the issue?**

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by suresh-gandhi**
Fix #98

**Changes**: 
- Fixed the incorrect package name of NeuroUtils class by changing it to io.neurolab from org.neurovillage.main

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by suresh-gandhi** [comment]
The build is failing as the current development branch itself is unstable. I believe it is due to missing references as all the public variables were changed to private in DefaultFFTData class without adding getters & setters. I would update my PR as soon as the issue #97 is resolved. @jddeep I would suggest you to shortly update with the PR to make the development branch stable as soon as possible.

**Comment by jddeep** [comment]
Yes this is the reason why we all should check we didn't break anything. #91 should have seen into it before making a PR. Now it is causing build failures. @suresh-gandhi I will make a PR by tonight.

**Comment by suresh-gandhi** [comment]
@mariobehling @CloudyPadmal @iamareebjamal Could you please review the PR.

**Review by iamareebjamal — APPROVED** [review]

**Comment by iamareebjamal** [comment]
Create an issue to setup CI which shows if build has failed

**Comment by suresh-gandhi** [comment]
@iamareebjamal Isn't Travis CI already set up for this repo? Correct me if I am wrong.

**Comment by iamareebjamal** [comment]
Then how is build failing?

**Pull request merged**
