### PR TITLE
fix: Club Settings and Feedback Settings together

### LINKED ISSUE #263: Club Settings and Feedback Settings together as they have the same purpose
**Describe the bug**
Currently, there are two options (and two activities subsequentially) in the settings menu namely **Settings** and **FeedbackSettings** devoted for the same purpose nearly, the former for editing the values and the later for displaying the values.

edit: Also merge "Configurations" into "Settings" and have them as two separate setting groups instead.

**Expected Behaviour**
It doesn't look that professional and appealing and therefore they should be clubbed together into a single **Settings** activity screen.

**Would you like to work on the issue?**
Would like to work on this.

### PR DESCRIPTION
**Pull request by suresh-gandhi**
Fixes #263.

**Changes**: 
* Feedback Settings option was redundant because it displayed nothing new that was displayed in the Settings option.
* Base functionality of Feedback Settings remains intact though as it is being instanced at many places elsewhere. The only change is that it is no more an Activity and essentially, don't extend any Activity parent class. I believe this is the way its also implemented in the desktop app.
* Merged NeuroSettings and Configurations into Settings.

**Screenshot**:
 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**Apk for testing**:
[app-debug.zip](https://github.com/fossasia/neurolab-android/files/3245122/app-debug.zip)

### CODE REVIEW

**Review by jddeep — COMMENTED** [review]
@suresh-gandhi Please update the PR body with the updated screenshot of the new Settings.

**Comment by CloudyPadmal** [comment]
@suresh-gandhi please provide APK to test.

**Comment by suresh-gandhi** [comment]
@CloudyPadmal did the changes. Thanks.

**Review by CloudyPadmal — APPROVED** [review]

**Review by jddeep — CHANGES_REQUESTED** [review]
@suresh-gandhi Please combine "Configurations" and "Settings" into one. You can keep them as two separate groups of prefs in one fragment itself. (Mentioned in the Issue as well)

**Comment by CloudyPadmal** [comment]
Yes we'll address that part too @suresh-gandhi

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
Combine configurations with settings

**Comment by suresh-gandhi** [comment]
@CloudyPadmal would do the required changes today. Thanks for the review.

**Comment by suresh-gandhi** [comment]
@CloudyPadmal did the changes. Please have a look.

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
These check box setting preferences are not following the standard settings. Checkbox preferences should be made clickable from the whole view. Check the PSLab Android app and how checkbox pref is working there. Check Android documentation on `CheckBoxPreference`

**Comment by CloudyPadmal** [comment]
Conflicts in resource files wouldn't occur if we really followed the second point in PR checklist

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
