### PR TITLE
Implemented Meditation Home Screen

### LINKED ISSUE #355: Missing Meditation Home screen
**Actual Behaviour.**  
Missing Meditation Home Screen

**Expected Behaviour**  
presence of Meditation home screen.
Steps to Fix #309 

**Additional context**  
> Not available

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #355 

**Changes**: Implemented Meditation Home Screen.

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
[app-debug.zip](https://github.com/fossasia/neurolab-android/files/3386626/app-debug.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Icons need to be of similar type. Either all filled or all outlined. Also why are we using a different font now? :thinking: For views, try to follow material design guidelines. (eg: borders around cards)

Check for travis build errors and fix them

**Comment by jddeep** [comment]
@CloudyPadmal We have started using the `Montserrat` font (we have used it in the Focus main screen as well) using Android `Font Provider`. We do need to make it uniform throughout though by applying it to other screen texts as well. Or do you suggest we revert back to Roboto?
Okay I will update the icons.

**Comment by CloudyPadmal** [comment]
Yea we've to make the font uniform

**Comment by jddeep** [comment]
@CloudyPadmal Here, I have used [MaterialCardView](https://developer.android.com/reference/com/google/android/material/card/MaterialCardView) for the categories. Do you suggest we remove the card borders?

**Comment by mariobehling** [comment]
Cards should have the same as the card on the main screen.

**Comment by mariobehling** [comment]
Icons should be white etc.
Please keep it simple and progress quickly to the actual functionality.

**Comment by jddeep** [comment]
Done. Please have a look at the PR body.

**Review by cweitat — APPROVED** [review]

**Review by CloudyPadmal — APPROVED** [review]
We'll have to iterate over the design and implementation. But for now let's get this merged as a WIP so that we can work on functionalities.

**Comment by jddeep** [comment]
Sure. Please merge this.

**Pull request merged**
