### PR TITLE
Added the OnBoardingActivity

### LINKED ISSUE #170: Adding the Intro Guide Screen
**Actual Behaviour**
* The application currently doesn't have an intro guide screen at the very start of the application (for the first time) as a tutorial on how to use application’s features and functionalities. 

**Expected Behaviour**
* The Intro Guide screen should be added at the start to make the app more intuitive and appealing to the user.

**Screenshots of the issue**
Intro Guide

**Would you like to work on the issue?**
I would like to work on this issue.

### PR DESCRIPTION
**Pull request by suresh-gandhi**
Fixes #170 

**Changes**: 
* Added the OnBoardingActivity.

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/neurolab-android/files/3292321/app-debug.zip)

### CODE REVIEW

**Comment by suresh-gandhi** [comment]
No issues on my local machine 😕

**Comment by suresh-gandhi** [comment]
@CloudyPadmal I am thinking of adding a permissions fragment (for USB connection) in this just like many other apps. In this way, the user would deal with the permissions (for now the usb permission) onboarding which is a logical way I suppose. What do u say?

**Comment by CloudyPadmal** [comment]
Yes please add permission requests in this activity

**Comment by suresh-gandhi** [comment]
@CloudyPadmal I think this PR can be merged for now after the build is resolved. Researched upon this somewhat. We can achieve the thing here as well as in the MainActivity but the later is a more suitable place for USB permission specifically because for requesting usb permission from the user we also need a usb device (for whom the permission is directed to) attached beforehand. I also checked it on PSLab it's done in the same way [reference](https://github.com/fossasia/pslab-android/issues/179). What I mean to say there is no straightforward way to add explicit usb permissions without a usb device like other permissions. Correct me if I am wrong. Also let me know if there are other permissions to add anyways taking into account the future.

**Comment by CloudyPadmal** [comment]
Yes for now we'll ask for permission related to local storage, mic etc. We'll proceed with another issue to work on those. Thanks for the PR..

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
