### PR TITLE
Implemented spaceAnimationVisuals

### LINKED ISSUE #134: Missing separate implementation of space visuals.
**Actual Behaviour**
Missing separate implementation of space visuals. The space animations should be implemented separately and should be called accordingly from the program mode activities.

**Would you like to work on the issue?**

Yes, i would like to work on this issue.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #134 

**Changes**: Implemented spaceAnimationVisuals to be accessed accordingly from program mode activity according to EEG data input.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by jddeep** [comment]
@iamareebjamal Please have a look. Thanks!

**Comment by iamareebjamal** [comment]
Ask for peer reviews first

**Comment by jddeep** [comment]
Yes sure @iamareebjamal . And @iamareebjamal I apologise for the conversation on the forums the previous day. It was really disheartening for me to see myself get involved in such a conversation for the first time. Henceforth, I request all contributors to work together. Very much looking forward to it! :+1:

**Comment by jddeep** [comment]
@suresh-gandhi @CoderVishalSehgal do give some reviews on the PR. And let me know about it! Thanks.

**Comment by vishal-sehgal** [comment]
@jddeep Yes sure buddy 👍

**Comment by vishal-sehgal** [comment]
@jddeep Can you please attach a gif too, want to see the behavior of the rocket animation which you implemented.

**Comment by jddeep** [comment]
> @jddeep Can you please attach a gif too, want to see the behavior of the rocket animation which you implemented.

@CoderVishalSehgal Refer to #28 for that.

**Comment by vishal-sehgal** [comment]
@jddeep I already checked out the #28 and read the comments there and what @CloudyPadmal exactly want, Can you please checkout this #139 :)

**Comment by jddeep** [comment]
Yes the Animation in #139 is good. @CoderVishalSehgal so you can do the whole Animation code in the SpaceVisuals class for which I have opened this PR to separately handle the data and the Animation accordingly. And in #139 do change the background to something similar like the current one as you can see in the desktop application.

**Comment by jddeep** [comment]
So before sending the PR for that do review this. So that after this, you can code your current Animation in the defined class as in this PR. So looking forward to seeing your review on this.

**Comment by vishal-sehgal** [comment]
@jddeep  Yes, I reviewed your code already, Actually your code is animating the rocket and I'm not animating the rocket that way and the SpaceVisualAnimation.class is still not in the development branch, so it won't conflict with my PR as there I created a different name. Also yes, I can do the same like in desktop app but it will take a lot of time due to some Graphics Rendering in 3 dimensions, I'll try to do same in future, believe me this #138 screen is really hypnotic and makes a quick focus of mind. 
@iamareebjamal @CloudyPadmal @mariobehling

**Comment by jddeep** [comment]
> @jddeep Yes, I reviewed your code already, Actually your code is animating the rocket and I'm not animating the rocket that way and the SpaceVisualAnimation.class is still not in the development branch, so it won't conflict with my PR as there I created a different name. Also yes, I can do the same like in desktop app but it will take a lot of time due to some Graphics Rendering in 3 dimensions, I'll try to do same in future, believe me this #138 screen is really hypnotic and makes a quick focus of mind.
> @iamareebjamal @CloudyPadmal @mariobehling

@CoderVishalSehgal My point of view is that after this get's merged you can put your animation code in the SpaceVisualAniamtion class and hence your Animation code can work from the program mode activity (activities in future) with input data passed into that. What do you say?

**Comment by vishal-sehgal** [comment]
@jddeep Actually I created a **CustomViewClass** and after merging your code it will of no use If my PR gets merge, Hope you try to understand me buddy :)

**Comment by jddeep** [comment]
> @jddeep Actually I created a **CustomViewClass** and after merging your code it will of no use If my PR gets merge, Hope you try to understand me buddy :)

@CoderVishalSehgal
You can code the exact same CustomViewAnimation in the spacSpaceVisuals class. I can see that you have not made a PR yet. I made this PR before you created that issue so I did not know that you were working on something like that. So please review and approve this so that you can go ahead making your PR after pulling upstream.
Hope you understand buddy!

**Comment by jddeep** [comment]
@CoderVishalSehgal then do give an approval to the PR. Cheers buddy!

**Comment by jddeep** [comment]
@iamareebjamal Please review and merge. Thank you.

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
