### PR TITLE
Ported and modified GUI classes

### LINKED ISSUE #95: Missing GUI classes
**Actual Behaviour**
Missing GUI classes

**Expected Behaviour**
There should be GUI classes.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #95 

**Changes**: Added GUI classes

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by jddeep** [comment]
Screenshot (148)
#91 Is causing build failure @iamareebjamal . @RohitJain1103 you should have seen that objects of `DefaultFFTData` class is being used in `FeedbackSettings` before encapsulating them. @iamareebjamal Can I proceed to revert back the changes in `DefaultFFTData` class? Please confirm.

**Comment by RohitJain1103** [comment]
@jddeep @iamareebjamal Encapsulation is never a wrong step. We should add getter and setter functions in DefaultFFTData and use them from other classes like FeedbackSettings and not revert back.

**Comment by jddeep** [comment]
@RohitJain1103 It has never been told that it is a wrong step. Before Encapsulating, the getter and setters should have been taken care of. Now see it causes build failures as the objects are used in various other classes.

**Comment by jddeep** [comment]
@CloudyPadmal @iamareebjamal Please suggest what can be done at this moment?

**Comment by iamareebjamal** [comment]
Add required getters and setters

**Comment by jddeep** [comment]
@iamareebjamal I will be first fixing that issue in a separate PR first then.

**Comment by jddeep** [comment]
@iamareebjamal Please review and merge.

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
