### PR TITLE
updated navdrawer

### LINKED ISSUE #112: NavDrawer needs update.
**Actual Behaviour**
The nav drawer currently has insignificant options,

**Expected Behaviour**
It should have correct navigation options,

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #112 

**Changes**: updated navdrawer.

**Screenshot/s for the changes**: 
Screenshot (155)

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Comment by suresh-gandhi** [comment]
@jddeep I would suggest you to work on the actual implementation of the program modes. I believe this is redundant because we already have an entry point to all the four modes in the launcher screen(through all the four buttons). Moreover, I think the nav drawer could be used for other better purposes(for instance storing the user preferences and account info when we connect the application to a database in the eventual stages or some other meaningful purpose).

**Comment by jddeep** [comment]
> @jddeep I would suggest you to work on the actual implementation of the program modes. I believe this is redundant because we already have an entry point to all the four modes in the launcher screen(through all the four buttons). Moreover, I think the nav drawer could be used for other better purposes(for instance storing the user preferences and account info when we connect the application to a database in the eventual stages or some other meaningful purpose). Rest your wish :)

@suresh-gandhi Just think if a user is in a particular program mode activity and is interacting with that. Does he need to navigate all the way back to the launcher activity. The navigation drawer is meant for navigation purposes. This is basic Android development. The storage of user preferences which you are suggesting can be kept in drop down menu fragments(eg:- Feedback Settings). I suggest you to once go through the basic Android development fundamentals once.

**Comment by suresh-gandhi** [comment]
@jddeep Haha. Alright. you are absolutely correct. Go ahead. God bless you :)

**Comment by jddeep** [comment]
@mariobehling @iamareebjamal Please review. Thank you.

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
