### PR TITLE
chore: Create auto_label.yml

### LINKED ISSUE #561: chore(tools): add auto_label.yml inside .github
**Describe the issue**
Currently we don't have the `auto_label.yml` file inside `.github` folder . Right now we have to label PR's manually.
Adding this will lead to automatic labelling of Pull Request's based on semantic labels in title. 

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by snitin315**
Fixes #561 
**Changes**:  added `auto_label.yml` file inside `.github` folder

### CODE REVIEW

**Review by adityastic — CHANGES_REQUESTED** [review]
Can you send me the documentation for this file?

**Comment by jddeep** [comment]
@snitin315 ??

**Comment by snitin315** [comment]
You can see it in action as `fix:` is used in some PR  and it sets label fix automaticaly ,

Screenshot from 2020-01-29 17-28-45

So  we can extend the configuration of `auto-label Bot`  by creating a seperate file  `auto_label.yml` and configuring it accordingly for the same.

**Comment by adityastic** [comment]
@snitin315 we already have an auto-label bot. I'm not sure what purpose this PR might serve.

**Pull request closed without merging**
