### PR TITLE
Improvement of the class FocusAudioFeedback 

### LINKED ISSUE #159: Refactor the wrong naming of About Us Activity layout xml file
**Actual Behaviour**
* The About Us Activity layout XML file is wrongly named as **activity_about__us**.

**Expected Behaviour**
It should be correctly named as **activity_about_us** as per the conventions and standards.

**Would you like to work on the issue?**
I would like to work on this issue.

### LINKED ISSUE #168: Improving the code of FocusAudioFeedback class
**Actual Behaviour**
* FocusAudioFeedback class is incorrectly ported from the neurolab desktop. It contains wrongly written (as well as redundant) code that was commented out in neurolab-desktop.
* _samplePlayer.amplitude_ variable in the updateCurrentFeedback method has been set two times. The second setting overrides the previous one and hence the previous one makes no sense at all. This is the reason I believe the statement was commented out in neurolab-desktop.
* Same is the case with _this.synth_ variable in the run( ) method in FocusAudioFeedback class. The second line jsynThread.getSynth( ) essentially does the same thing as Jsyn.createSynthesizer( )  method.

**Expected Behaviour**
* All of these changes should be taken into account for the code improvement/optimization.

**Would you like to work on the issue?**
I would like to work on this issue.

### PR DESCRIPTION
**Pull request by suresh-gandhi**
Fixes #168

**Changes**: 
* Removing the incorrect and redundant line regarding the setting the _samplePlayer.amplitude_ variable as well _this.synth_ variable in updateCurrentFeedback( ) and the run( ) methods respectively.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by suresh-gandhi** [comment]
@iamareebjamal Could you please review the PR. Let me know if something needs to be changed.

**Review by adityastic — DISMISSED** [review]
Peer review done

**Comment by CloudyPadmal** [comment]
Conflicts to resolve :bell:

**Comment by suresh-gandhi** [comment]
@CloudyPadmal did the changes and resolved the conflicts. Could you please review and merge. Let me know if something else needs to be changed. Thanks.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
