### PR TITLE
Added the Setters in Server Settings class

### LINKED ISSUE #187: Missing Setters in the ServerSettings class
**Actual Behaviour**
* The ServerSettings class is devoid of setters.

**Expected Behaviour**
* The ServerSettings class should have setters (would be required for saving the configuration state when user check/uncheck the checkboxes). 

**Would you like to work on the issue?**
Would like to work on this.

### PR DESCRIPTION
**Pull request by suresh-gandhi**
Fixes #187 

**Changes**: 
* Added the Setters in Server Settings class to provide the flexibility to change the initial configuration settings if required.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Comment by suresh-gandhi** [comment]
@iamareebjamal @CloudyPadmal @mariobehling Could you please review the PR.

**Comment by suresh-gandhi** [comment]
@iamareebjamal @CloudyPadmal @mariobehling Could you please review the PR.

**Comment by ShridharGoel** [comment]
Create sub-issue and link the PR to it.

**Comment by suresh-gandhi** [comment]
@ShridharGoel alright.

**Review by ShridharGoel — APPROVED** [review]

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
