### PR TITLE
fix : Removing CSV files from the mediatations list

### LINKED ISSUE #510: Meditation List contains csv datasets alongwith music tracks.
**Describe the bug**
Meditation List contains csv datasets with music files.
**Expected Behavior**
Datasets should not appear in meditation list.

**Steps to reproduce bug**

1) Enable developer's mode and then go to mediation activity.
2) Open any meditation genre.

**Screenshots of the issue**
Screenshot_2019_10_19_12_45_46_64_243bed73eac0221c54c37b9ad745f08a_min__1571470326_52438

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by dipu989**
Fixes #510 

**Changes**:
Removed CSV datasets from meditations list.

**Screenshot/s for the changes**:
ezgif com-optimize

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
[apkDebug.zip](https://github.com/fossasia/neurolab-android/files/3753949/apkDebug.zip)

### CODE REVIEW

**Comment by dipu989** [comment]
Please review this PR @jddeep @CloudyPadmal @iamareebjamal @adityastic 
Also, Codacy checks are asking to put a few variables in the local scope. Will that not be against the structure we follow in our projects?

**Comment by adityastic** [comment]
@dipu989 as long as they are not required globally, we should always keep the scope local

**Comment by dipu989** [comment]
@adityastic Please review!

**Review by adityastic — APPROVED** [review]
Looks good, Good Job 👍

**Comment by adityastic** [comment]
@jddeep @CloudyPadmal

**Review by jddeep — APPROVED** [review]

**Pull request merged**
