### PR TITLE
Readme file updated with short desc about screenshots

### LINKED ISSUE #443: Update Readme file
**Describe the issue**

Add short description text under screenshots.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #443 

**Changes**: Readme file updated with short desc about screenshots.

**Screenshot/s for the changes**: 
https://github.com/jddeep/neurolab-android/blob/development/README.md

**APK for testing**: 
N/A

### CODE REVIEW

**Comment by mariobehling** [comment]
Please check: 
* Align cell content to top
* Width of screenshots is cut down or squeezed. Please ensure the entire screenshot fits in.

**Comment by mariobehling** [comment]
* Screenshot of "Relaxation" is still missing on top.

**Comment by jddeep** [comment]
@mariobehling done :+1:

**Comment by mariobehling** [comment]
Thanks.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
