### PR TITLE
chore: fastlane init

### LINKED ISSUE #460: Initialize Fastlane support for the repo
**Describe the issue**

Missing Fastlane support for the repo

**Would you like to work on the issue?**
Issue for Codeheat.

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #460 

**Changes**: 
- Added fastlane files

### CODE REVIEW

**Comment by adityastic** [comment]
@CloudyPadmal can you please add secrets.tar to this project and give me the encrypted variable

**Comment by adityastic** [comment]
@iamareebjamal please include secrets.tar in this repository. we also need to create a new listing for Neurolab on Google Play Store

**Comment by iamareebjamal** [comment]
Need release key for this

**Comment by adityastic** [comment]
> Need release key for this

yes areeb, should I create one?

**Comment by iamareebjamal** [comment]
Yes

**Comment by mariobehling** [comment]
Please don't add this project to Google Play yet. We are in the process to check if the name of the app is suited or has rights to it in any way. This will take some time. Right now this app is also not really usable. So, committing it to Fdroid is sufficient for devs who want to have a quick test. Thank you.

**Comment by adityastic** [comment]
> Please don't add this project to Google Play yet. We are in the process to check if the name of the app is suited or has rights to it in any way. This will take some time. Right now this app is also not really usable. So, committing it to Fdroid is sufficient for devs who want to have a quick test. Thank you.

great ok

**Comment by adityastic** [comment]
@jddeep @CloudyPadmal plz review

**Review by jddeep — APPROVED** [review]

**Pull request merged**
