### PR TITLE
In Settings Page the summary is shown,it gets updated also when its value changes

### PR DESCRIPTION
**Pull request by Aditya185**
Fixes #[Add issue number here. Note: This will automatically closes the issue. If you do not solve the issue entirely, please change the message to e.g. "First steps for issues #IssueNumber]
  #73 

**Changes**: [Add here what changes were made in this issue and if possible provide links.]
changes in code
in NeuroSettingsFragement
and its xml file

**Screenshot/s for the changes**: [Add screenshot/s of the layout where you made changes or a `*.gif` containing a demonstration]
screenshot_20190304-192853

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Comment by jddeep** [comment]
There is a Feedback Settings Activity for that where the current NeuroSettings can be checked. Initially the same functionality as this PR was kept but keeping in mind about the codebase of the desktop version of the app, the Feedback settings was introduced. Hope you understand. Cheers!

**Review by jddeep — COMMENTED** [review]
There is a Feedback Settings Activity for that where the current NeuroSettings can be checked. Initially the same functionality as this PR was kept but keeping in mind about the codebase of the desktop version of the app, the Feedback settings was introduced. Hope you understand. Cheers!

**Comment by Aditya185** [comment]
@jddeep ,i want to work more on this project, please elaborate about what does the import,gallery,slideshow,tools in the side bar suppose to do.

**Comment by CloudyPadmal** [comment]
@Aditya185 they were default options added when creating the blank app. We don't need those and we have to replace them with necessary options as development is progressing.

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
Please reformat the code when submitting the PR to add missing spaces and indentation and remove unnecessary.

**Review by Aditya185 — COMMENTED** [review]
Yes,Please Change

**Comment by jddeep** [comment]
I had told you there is `Feedback Settings` for the same.

**Comment by mariobehling** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
