### PR TITLE
Implemented Use of Shared Prefs in Launcher

### LINKED ISSUE #128: Lacking Shared Preferences in the App.
**Actual Behaviour**
The app lacks the implementation of shared preferences.

**Expected Behaviour**
The shared prefs can be used to store last launch settings of the application aiding the user choice for the next session.

**Would you like to work on the issue?**

Yes, I would be working on that.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #128 

**Changes**: Now whenever the user opens the app. His last checked preferences shall be stored.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by jddeep** [comment]
@mariobehling @iamareebjamal @CloudyPadmal Please review. Thanks!

**Comment by jddeep** [comment]
@iamareebjamal Please review this.

**Comment by jddeep** [comment]
@iamareebjamal Please review this.

**Review by RohitJain1103 — COMMENTED** [review]
@iamareebjamal I think the use of Shared preferences would be wrong here as it is needed to have a lot of data as @sureshgandhi already pointed out in https://github.com/fossasia/neurolab-android/pull/123. One question @jddeep - Why are you duplicating the same thing that @sureshgandhi is already solving in this PR.

**Comment by jddeep** [comment]
@RohitJain1103 @iamareebjamal I could not get the purpose of #123 . The Launcher Activity server settings should be stored in Shared Prefs because only the checkboxes specifically simulation, load resources, audio feedback, 24 bit mode and advanced mode. Their last response should be stored after every session to aid the user the next time he uses the app. We don't need to store anything from the Program modes from the app. And @RohitJain1103 If you are talking about such large data even Cloud tech like Firestore can be used in the future if needed. Please don't try to compare each and everything from the desktop application. Android development has got some separate principles and dev strategies.

**Comment by jddeep** [comment]
@iamareebjamal Please share your thoughts.

**Comment by jddeep** [comment]
@RohitJain1103 @suresh-gandhi If you want further clarification, let us discuss on the gitter channels and let's leave the forums for reviews from mentors. Cheers!

**Comment by RohitJain1103** [comment]
@jddeep You still didn't answer the question. I am afraid but It seems to me you are beating around the bush. What I am saying is a simple question. The issue is already being tackled in this PR. What is the need to duplicate it. And assume even if shared preferences are to be used(our mentors @iamareebjamal @CloudyPadmal would let us know in that case) then also it should be tackled by this PR not by a separate PR. I would suggest you to understand neurolab-desktop first, install it in your machine, run the application. And if you have already installed it please understand the code-base comprehensively. 

> I could not get the purpose of #123 . The server settings (the checkboxes specifically simulation, load resources, audio feedback, 24 bit mode and advanced mode) preferences from the Launcher Activity should be stored in Shared Prefs only because their last response should be stored after every session to aid the user the next time he uses the app for configuring and setting up the next session and he doesn't need to check the necessary settings again.

Its not so simple. Just see how Launcher class and ini file are related in neurolab-desktop. It seems to me you have not at all installed the neurolab-desktop repo in your machine. 

>If you are talking about such large data even Cloud tech like Firestore can be used in the future if needed...

See again. Its not big data dear. Nobody is suggesting to go for the Cloud Storage. Its about using right things for right purpose. You please understand neurolab-desktop in depth first. I would strongly urge you to do that.

>Please don't try to compare each and everything from the desktop application. Android development has got some separate principles and dev strategies.

Its not about comparing the two things together. Its about going in the right direction and porting the software correctly which you aren't. Its not about a single feature which has subjectivity in its implementation for different platforms. Its about the underlying design pattern involved. I hope you understand.

> Suggestion

Why don't you work on the program modes and concrete PR's. It would make the porting process swift and help the organization a lot.

**Comment by jddeep** [comment]
Dear @RohitJain1103  
Answer to your first question:
I was working on Shared preferences before the #123 was made. And as soon as @iamareebjamal commented about using them I made the PR incidently. Please see here https://github.com/fossasia/neurolab-android/pull/123#issuecomment-478199105 for verification. 
And why are your use of words in a quarrelling fashion buddy? If you want any particular change in a PR. Please comment about it and leave the rest to the Author and mentor.
Talking about helping out the organization and the project development. I have been contributing to it right from when the project was at the level of scratch. Again for verification please refer here 
https://github.com/fossasia/neurolab-android/pulls/jddeep . Instead of thinking about helping out the organization start doing it by quality PRs which i can see none from your side. I suggested you not to extend the discussion here. But still you didn't listen. Hope you understand. Looking forward to your quality contributions rather than just reformatting the code and changing the images. Cheers!

**Comment by jddeep** [comment]
>  I could not get the purpose of #123 . The server settings (the checkboxes specifically simulation, load resources, audio feedback, 24 bit mode and advanced mode) preferences from the Launcher Activity should be stored in Shared Prefs only because their last response should be stored after every session to aid the user the next time he uses the app for configuring and setting up the next session and he doesn't need to check the necessary settings again. We don't need to store anything from the Program modes from the app. And @RohitJain1103 If you are talking about such large data even Cloud tech like Firestore can be used in the future if needed. Please don't try to compare each and everything from the desktop application. Android development has got some separate principles and dev strategies.

@iamareebjamal Please share your thoughts.

**Comment by RohitJain1103** [comment]
@jddeep It is the people like you who are destroying the reputation of Foss by unnecessarily fighting in the comments again and again. Do you know why any new contributor tries to work on this repo and then leaves it? It is because of your regular pestering in comments and telling them to do real contribution while you are busy adding text to AboutUs, porting classes with no lines of code in them. Your logic is pretty clear - @jddeep wants to do GSoc in Foss so disturb every other contributor, there is no competition and hence you get the opportunity. Well done man! Who am I even discussing with. A person who is "contributing" to this repo and don't even know how to squash commits, A "contributor" who doesn't even know how to run neurolab-desktop and is porting it to android version. (I have screenshot of the gitter message which you had sent asking procedure of running neurolab-desktop).

Talking about serious contributions, your comments in this repo = exp(number of commits). If you want proof I can add all the screenshots of all your pestering sessions. 
You tell you have been working on this repo from scratch but the project before March was hollow only consisting of UI's. Talking about my contributions, I have optimised many mathematical functions which require good maths base which I'm sure you wouldn't have. 

Note - If you want proof of each and every statement, I have screenshot of everything.

And do not comment on this again. Your insensible statements do not make any sense. And if you do so I will have to contact higher authorities to take care of this matter.

**Comment by iamareebjamal** [comment]
From now on, please keep comments strictly related to PR code quality, and bugs. Not that if a PR is necessary or the approach. Both of you reflect poorly.

**Pull request closed without merging**
