### PR TITLE
Bug Fixed : Issue #446 App closes on clicking back button from Setting

### LINKED ISSUE #446: App closes on clicking back button from Settings screen.
**Actual Behaviour.**  
App closes on clicking back button from Settings screen. 

**Expected Behaviour**  
Make app move back to Home screen.

**Would you like to work on the issue?**
Issue for Codeheat.

### PR DESCRIPTION
**Pull request by anandtushar111**
Fixes #446  
**Changes**: I have made two changes. One in the Neurolab.java and other in the manifest.
Screenshots for the same are attached below.

**Screenshots for the changes:**  
1) [Neuro lab screenshot](https://drive.google.com/file/d/1ppx1Zz7q4kGsyoyZnVdBPpcgzKYRiHfh/view?usp=sharing)
I have removed the finish() line below line 276 -  startActivity(new Intent(this, SettingsActivity.class)); . This I have done to prevent the Neurolab Activity to get finished after Setting Activity has been called. 
2) [Manifest screenshot](https://drive.google.com/file/d/1aDPa6jPyAUIMd-UzjkmyLvKbljfYuy5N/view?usp=sharing)
I have added a line below line 46 - android:launchMode="singleTop" . This I have done to make the Neurolab Activity use the same instance when we click the back button on Setting Activity.

Android Launch mode guide: [Click here](https://medium.com/@iammert/android-launchmode-visualized-8843fc833dbe)

**Checklist**: 
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[Updated APK Link](https://drive.google.com/file/d/1-orHKqSOgmrSUWaox49U5DCJsGWledVp/view?usp=sharing
)

### CODE REVIEW

**Comment by jddeep** [comment]
@anandtushar111 Please write the PR description body properly and attach screencast video and apk for testing.

**Comment by jddeep** [comment]
> @anandtushar111 Please write the PR description body properly and attach screencast video and apk for testing.

@anandtushar111 Any updates??

**Comment by anandtushar111** [comment]
I have deleted line 247 "finish()" in NeuroLab activity in main package.

**Comment by anandtushar111** [comment]
makabo makabo

**Comment by jddeep** [comment]
@anandtushar111 Please check other open PRs and learn how to write in the PR description box. Thank you. 
Also, check the app by going to settings screen multiple times from launcher and then click back button when on launcher screen.What do you observe?

**Review by jddeep — COMMENTED** [review]
@anandtushar111 Please check other open PRs and learn how to write in the PR description box. Thank you.
Also, check the app by going to settings screen multiple times from launcher and then click back button when on launcher screen.What do you observe?

**Comment by adityastic** [comment]
please also follow semantic naming. Reference:
https://github.com/probot/semantic-pull-requests

**Comment by anandtushar111** [comment]
> @anandtushar111 Please check other open PRs and learn how to write in the PR description box. Thank you.
> Also, check the app by going to settings screen multiple times from launcher and then click back button when on launcher screen.What do you observe?

I have noticed that after trying to getting back from setting activity multiple times from launcher, in some cases neurolab activity restart. I have solved this issue too.

**Comment by jddeep** [comment]
@anandtushar111 Please provide an updated apk for testing. Thanks.

**Comment by anandtushar111** [comment]
https://drive.google.com/file/d/11WWLxh8ZYXY5SvrgjSEhNqnt2wlUurak/view?usp=sharing
please download the apk from the given link

**Comment by jddeep** [comment]
@anandtushar111 What's up with your PR body/description? Don't you follow other PR patterns? I have told you earlier even.

**Comment by anandtushar111** [comment]
Fixes #446  
**Changes**: I have made two changes. One in the Neurolab.java and other in the manifest.
Screenshots for the same are attached below.

**Screenshots for the changes:**  
1) [Neuro lab screenshot](https://drive.google.com/file/d/1ppx1Zz7q4kGsyoyZnVdBPpcgzKYRiHfh/view?usp=sharing)
I have removed the finish() line below line 276 -  startActivity(new Intent(this, SettingsActivity.class)); . This I have done to prevent the Neurolab Activity to get finished after Setting Activity has been called. 
2) [Manifest screenshot](https://drive.google.com/file/d/1aDPa6jPyAUIMd-UzjkmyLvKbljfYuy5N/view?usp=sharing)
I have added a line below line 46 - android:launchMode="singleTop" . This I have done to make the Neurolab Activity use the same instance when we click the back button on Setting Activity.

Android Launch mode guide: [Click here](https://medium.com/@iammert/android-launchmode-visualized-8843fc833dbe)

**Checklist**: 
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[Updated APK Link](https://drive.google.com/file/d/1-orHKqSOgmrSUWaox49U5DCJsGWledVp/view?usp=sharing
)

**Comment by anandtushar111** [comment]
Any other details required @jddeep?

**Comment by jddeep** [comment]
@anandtushar111 You needed to update the original PR description body at the top instead of making as a separate comment. I have done it for you in this PR. Keep that in mind henceforth.

**Review by jddeep — APPROVED** [review]

**Pull request merged**
