### PR TITLE
Added and implemented Classes DefaultFFTData, MathBasics and interface FFTData.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #17

**Changes**: Added and implemented Classes DefaultFFTData, MathBasics and interface FFTData.

**Screenshot/s for the changes**: [Add screenshot/s of the layout where you made changes or a `*.gif` containing a demonstration]

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Comment by jddeep** [comment]
@mariobehling and @CloudyPadmal I followed https://github.com/fossasia/pslab-android#how-to-git-squash to squash my commits into one. But my efforts were in vain as it still shows the successive commits instead of getting squashed into one. Everything seems to be fine on my side. Any help will be much appreciated. Thanks!

**Comment by CloudyPadmal** [comment]
Hi, this PR has all the changes from #19 . Need to have changes only related to this PR. Can you post the screenshots of terminal when you type following commands?

1. git remote -v 
2. git branch -vv

**Comment by jddeep** [comment]
screenshot 99
@CloudyPadmal here is the screenshot of my terminal. If you have any solution please tell me otherwise I got a way I would like to share. But anyway first if you have a solution let me know. Thanks !

**Comment by CloudyPadmal** [comment]
@jddeep the problem is the development branch is not tracking the upstream. Type the following command and try the squashing procedure once again.

`$ git checkout development`
`$ git branch -u upstream/development`

After that;

`$ git fetch upstream`
`$ git pull`

Resolve conflicts and continue with squash

**Comment by jddeep** [comment]
screenshot 101
@CloudyPadmal sir, after doing `$ git pull` the above screen appears. I tried giving a commit message and pressing Ctrl+O and then Ctrl+X but it seems to have no effect. Can you suggest how to proceed from here. Thank you !

**Comment by CloudyPadmal** [comment]
It's vim. To save and quit type `:wq`

**Comment by jddeep** [comment]
@CloudyPadmal I found that everything was already up-to-date. I have squashed all the commits into this one. Now it is mergeable. Thanks.

**Comment by jddeep** [comment]
@mariobehling kindly check into this PR and review it if necessary or merge it. This PR has been pending for quite a while. Thank you.

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
