### PR TITLE
Fix[#369]: Updated Datasets

### LINKED ISSUE #369: Update datasets with headers
**Actual Behaviour.**  
Datasets need more info

**Expected Behaviour**  
- Unix time code
- Time/Date
- Channel 1
...
- Channel n
- Latitude
- Longitude
- Device
- OS
- Hardware
- Firmware
- MAC Address
- Name

**Steps to reproduce it**  
> Not available

**Additional context**  
> Not available

**Would you like to work on the issue?**
Issue for GSoC

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #369 

**Changes**: Updated Datasets.

**Screenshot/s for the changes**: 
> Not available

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
> Not available

### CODE REVIEW

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
1. Double check every dataset for errors. I checked the very first one and it has a `s` (,,4190.25641,,,,,,,,,,,,s)
2. There are extra commas at the header. Remove them.

**Comment by jddeep** [comment]
@CloudyPadmal I didn't quite get the problem with headers:
csvcheck
And yes, I too saw a particular row in the Dataset 1 ends with a `s`. Will rectify that and cross check all once again.

**Comment by CloudyPadmal** [comment]
After the column `Name` there are empty columns.

**Comment by jddeep** [comment]
@CloudyPadmal Have a look now, please. Thanks.

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
