### PR TITLE
New App Icon and Improve Colorful UI in Menu

### PR DESCRIPTION
**Pull request by abhiramready**
Fixes #[93]

**Changes**: [
- Add App icon Neuro Lab
- Removed old redundant textviews 
-Add colorful UI in the menu
]

**Screenshot/s for the changes**: [

logo
Screenshot_20190322-233512
Screenshot_20190322-233017

]

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: [

[app-debug.zip](https://github.com/fossasia/neurolab-android/files/2997794/app-debug.zip)

]

### CODE REVIEW

**Comment by mariobehling** [comment]
We need to design a common design approach. This has low priority now. We focus on functionalities at the moment.

**Comment by mariobehling** [comment]
Oh sorry, I missed that you also made other changes. So, let me accept this even though final design will be different. Thanks!

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by abhiramready** [comment]
Yes even I thought that we need to have common design approach or like a theme and proper design guidelines, 
Yes I will  resolve the conflicts

**Comment by mariobehling** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
