### PR TITLE
Added and implemented supporting classes

### LINKED ISSUE #41: Missing multiple supporting classes for AudioFeedback.
**Actual Behaviour** The classes Feedback, FocusFeedback, Config, ResourceManager are missing.
They are required for implementing Audio Feedback.

**Would you like to work on the issue?**
Yes, I would like to work on this issue.

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #41 and #42 

**Changes**: I added the classes and missing functionalities.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

### CODE REVIEW

**Comment by jddeep** [comment]
@mariobehling @CloudyPadmal could you please and review and merge the PR. Cheers!

**Comment by suresh-gandhi** [comment]
@jddeep I think you should add the external dependencies as well in order to port the complete functionality. You could take a look at the external dependencies used in neurolab-desktop [here](https://github.com/fossasia/neurolab-desktop).

**Comment by jddeep** [comment]
> @jddeep I think you should add the external dependencies as well in order to port the complete functionality. You could take a look at the external dependencies used in neurolab-desktop [here](https://github.com/fossasia/neurolab-desktop).

@suresh-gandhi are you talking about the external libraries and components? The desktop libraries will differ with android. Much of the desktop libraries are related with frontend and are not needed in Android as in the later the Appcompat and other widgets (in XML) handle it. The other backend libraries will be added shortly. Cheers!

**Comment by jddeep** [comment]
@mariobehling @CloudyPadmal please take a look and review the PR. Thanks.

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
Remove the commented code

**Comment by jddeep** [comment]
@CloudyPadmal Required changes have been seen into. You can now review the PR. Cheers!

**Comment by jddeep** [comment]
@CloudyPadmal Please have a look at the PR. Cheers!

**Pull request merged**
