### PR TITLE
Adding share in the Navigation Bar

### PR DESCRIPTION
**Pull request by apoorv-katiyar**
**Changes**: Sharing option app was not working previously.Now you can share the app. 

**Screenshot/s for the changes**: Imgur

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: NA

### CODE REVIEW

**Review by jddeep — COMMENTED** [review]
There is no practical significance in "sharing the app". Here I can see you are just sharing the app name. Please close the PR. Thanks.

**Comment by apoorv-katiyar** [comment]
@jddeep As the app is not published yet.That's why only the name is provided later on it will be fixed. Thanks.

_Sent from my Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jddeep** [comment]
@Apoorv0001 I don't think this is much of use even in later stages. Like what would be shared through it? @CloudyPadmal can confirm us more about that.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by iamareebjamal** [comment]
Unneeded. Focus on bugs and enhancements

**Pull request closed without merging**
