### PR TITLE
Enhance: Added OSCReciever base class

### LINKED ISSUE #173: Add the Networking functionalities (Forwarders as well as Receivers)
**Actual Behaviour**
* The networking subpackage is incomplete and lacks several essential classes like OSCForwarder, OSCReceiver, SerialForwarder, SerialPortInterface, and SerialPortReader.

**Expected Behaviour**
* The networking package should be completely ported both the forwarders and receivers which would include finding and adding the correct external dependencies for the android version of the application and porting all these classes correctly for android.
* This would help to carry out our tests either on the hardware or on the test dataset recorded from a real device as @CloudyPadmal mentioned [here](https://github.com/fossasia/neurolab-android/issues/152). 

**Classes to Port and Checklist of the work** 
- [x] Finding and adding the correct external dependencies for the Android version.
- [x] Adding forwarders - OSCForwarder, SerialForwarder
- [x] Adding receivers - OSCReceiver 
- [x] Adding other utility classes - SerialPortInterface, SerialPortReader

**Would you like to work on the issue?**
I would like to work on this issue.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #173 partly.

**Changes**: Added OSCReciever base class for handling data.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by jddeep** [comment]
@iamareebjamal @mariobehling @CloudyPadmal Please review. Co-devs and peers are welcome to review.

**Review by suresh-gandhi — COMMENTED** [review]
@jddeep I think it contains many partially implemented methods. The UI Display part (after the receiving operations) is missing. Either make a new Activity or Fragment and link the classes appropriately or add the functionalities here. Please update the PR after adding them. Also could you please reference this PR to [this](https://github.com/fossasia/neurolab-android/issues/173) issue. 17 has been closed already.

**Comment by jddeep** [comment]
> @jddeep I think it contains many partially implemented methods. The UI Display part (after the receiving operations) is missing. Either make a new Activity or Fragment and link the classes appropriately or add the functionalities here. Please update the PR after adding them. Also could you please reference this PR to [this](https://github.com/fossasia/neurolab-android/issues/173) issue. 17 has been closed already.

@suresh-gandhi I have intentionally mentioned "base class" as this class should serve for the functions and data (getters and setters) to the Activity/Fragment. I shall make the Activity soon in fresh PR. And thanks I will update the issue. It is much like the Feedback Settings and an other Activity for the same.

**Review by suresh-gandhi — APPROVED** [review]

**Comment by jddeep** [comment]
@iamareebjamal @CloudyPadmal Please merge this.

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
