### PR TITLE
Added MPAndroidChart Dependency for UI enhancement in the Program Modes

### LINKED ISSUE #185: Missing Graphing/Chart Library for implementing intuitive and engaging ui's
**Actual Behaviour**
* Currently in the all the four program modes we just have a rocket animation which in itself doesn't make much sense as it doesn't depict or specifically quantify something. Instead, all four program mode activities should have appealing and intuitive user interfaces (bar-graphs, line-charts, heat-maps) for enhancing the user experience when dealing with those modes. 

**Expected Behaviour**
* Intuitive UI’s like bar-graphs, line-charts, heat-maps, etc for portraying the degree of stress, anxiety, focus time curves, etc in the all the four program mode activities to improve the neuro-visual feedback.

**Would you like to work on the issue?**
I would like to work on this issue.

### PR DESCRIPTION
**Pull request by suresh-gandhi**
Fixes #185.

**Changes**: 
* Found two great open-source libraries regarding this - MPAndroidChart and AnyChartAndroid. The later however runs on 19+ devices. 
* Added a charting library for implementing appealing UI's in the Program Mode Activities.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Comment by suresh-gandhi** [comment]
@iamareebjamal Could you please review the PR.

**Review by adityastic — COMMENTED** [review]
@suresh-gandhi You should add some demo implementation as well. Check #152 and make a demo implementation. A PR just to add a library, I'm not sure about this

**Comment by suresh-gandhi** [comment]
@adityastic I generally do that only. But this time I wasnt sure that the library would be accepted first. I mean mentors may suggest some other better charting library. So I wanted to make that sure before implementing further. I just want to take an approval once.

**Comment by adityastic** [comment]
Ok great then

**Comment by iamareebjamal** [comment]
We'll add the library when we need it. Just adding the library is not required

**Comment by suresh-gandhi** [comment]
@iamareebjamal Okay. So shall I use this library, update the program mode activities and then update the PR or shall I leave that work for later stages and close the PR?
I was actually focussing on neuro-visual feedback somewhere along the lines of [this](https://github.com/fossasia/neurolab-android/issues/136) issue. Particularly I wanted to replace the rocket animation in the four program mode activities with something more aligned and engaging. Either we can test on a dummy data for now or we can leave this thing for later stages when the hardware work is substantially completed and we have real-time data to test. Whatever is the case you suggest. Thanks for your review.

**Comment by iamareebjamal** [comment]
later

**Comment by suresh-gandhi** [comment]
@CloudyPadmal Please have a look.

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
