### PR TITLE
Fixed and revamped the launcher UX/UI

### LINKED ISSUE #198: Bad and messed up UI for the Launcher screen.
**Actual Behaviour.**  
Bad and messed up UI for the Launcher screen.
Webp net-resizeimage

**Expected Behaviour**  
The UI needs to revamped,

**Steps to reproduce it**  
Run the app from the development branch.
Open the app.

**Would you like to work on the issue?**
Yes, I will work on it,

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #198 

**Changes**: Fixed and revamped the launcher UX/UI.
**Previous screen:**
Webp net-resizeimage

**New Screen:**
Webp net-resizeimage

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Review by suresh-gandhi — APPROVED** [review]
Good to go.

**Comment by adityastic** [comment]
wow that actionbar xD

**Comment by mariobehling** [comment]
This can only be a step to the final UI. Merging this as WIP.

1. We need to separate the different settings and there needs to be an explanation what they stand for. You can refer to any popular app like Twitter, FB, Instagram. See how settings areas usually look like.

2. The usage/meaning of Focus/Relax/VJ/SERIAL is unclear.

Please adhere to standard capitalization in apps:
* Simulation
* Audio Feedback
* 24 Bit
* Advanced Mode

This should be a separate button I guess:
* Load Resources from Phone

Avoid all capitals:
* Focus/Relax/VJ/SERIAL

**Comment by mariobehling** [comment]
Please follow up here: https://github.com/fossasia/neurolab-android/issues/207

**Pull request merged**
