### PR TITLE
fix: travis build for pr

### PR DESCRIPTION
**Pull request by adityastic**

### CODE REVIEW

**Review by jddeep — COMMENTED** [review]
@adityastic Try to change the gradle version (downgrade) and the distribution url.

**Comment by adityastic** [comment]
@jddeep sure, let me try that tonight

**Comment by jddeep** [comment]
@adityastic Let us get this fixed asap.

**Comment by adityastic** [comment]
> @adityastic Let us get this fixed asap.

Sorry, I've been busy lately with assessments. I'll manage to get it fixed soon

**Pull request merged**
