### PR TITLE
refactor: removed manifest warnings

### LINKED ISSUE #432: Warnings in Android manifest file
**Describe the issue**

There are few warnings shown in manifest.xml file in project. They can be ignored.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes #432 

**Changes**: 
- Added ignore clauses for backup and app indexing

**Screenshot/s for the changes**: 
> Not available

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [X] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [X] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [X] My code does not contain any extra lines or extra spaces
- [X] I have requested reviews from other members

**APK for testing**: 
> Not available

### CODE REVIEW

**Comment by adityastic** [comment]
@CloudyPadmal the error must be regarding not having ACTION-VIEW in your manifest. A better way to solve this is maybe by adding:
<action android:name="android.intent.action.VIEW" />
to the default activity

**Review by adityastic — COMMENTED** [review]
@CloudyPadmal the error must be regarding not having ACTION-VIEW in your manifest. A better way to solve this is maybe by adding:
```<action android:name="android.intent.action.VIEW" />```
to the default activity

**Review by adityastic — APPROVED** [review]
👍 Travis is having some issues maybe, not able to clone for some reason

**Comment by CloudyPadmal** [comment]
:thinking: there are extra builds.

**Pull request merged**
