### PR TITLE
fix: last item visited on navigation drawer

### LINKED ISSUE #551: Last item visited from menu bar always remains selected
**Describe the bug**
When I click on a item in menu bar, say Memory graph, then when I click on device's back button, the item in menu bar remains selected.

**Expected Behavior**
The device should forget the selected item and in the menu bar, none of the items should remain selected.

**Steps to reproduce it**
Open the side bar, open Focus/ Relax/ Memory graph and then click on the device's back button. Reopen the side menu, you will see the item you visited was selected.

**Screenshots of the issue**
Screenshot_2019-12-17-10-04-36-40_243bed73eac0221c54c37b9ad745f08a

**System Information**
<table>
<tr>
  <td>Device</td><td>Realme 1</td>
</tr>
<tr>
  <td>Android version/OS</td><td>Pie 9.0</td>
</tr>
</table>

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by rob729**
Fixes #551 

**Screenshot/s for the changes**:
<a href="https://imgflip.com/gif/3jqiaq"></a>

**Checklist**: 
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app.zip](https://github.com/fossasia/neurolab-android/files/3974597/app.zip)

### CODE REVIEW

**Comment by rob729** [comment]
@adityastic @jddeep Please review this PR.

**Review by adityastic — APPROVED** [review]
Great Job 👍

**Comment by adityastic** [comment]
@rob729 lets keep the titles semantic, for this issue the title should be "fix: last item visited on navigation drawer". Keep up the good work :)

**Comment by rob729** [comment]
@jddeep @CloudyPadmal Please review this PR.

**Review by jddeep — APPROVED** [review]

**Pull request merged**
