### PR TITLE
Updated Data Logging with possible fields

### LINKED ISSUE #381: Update Data Logging with Lat, Long and other possible fields
**Actual Behaviour.**  
Missing Data Logging with Lat, Long and other possible fields.

**Expected Behaviour**  
Data Logging with Lat, Long and other possible fields.

**Steps to reproduce it**  
> Not available

**Additional context**  
> Not available

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #381 

**Changes**: Updated Data Logging with possible fields.

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
https://drive.google.com/open?id=1XIeko9zLWavCe5YUvzCdWwc81AASuNuo

### CODE REVIEW

**Review by CloudyPadmal — COMMENTED** [review]
Same content as #377 ?

**Comment by jddeep** [comment]
> Same content as #377 ?

Nope, in #377 the data is recorded as it is in the dataset in the Android. But here it is updated with other fields like uts, date/time, lat, long...and then recorded (Check the screenshot in both PRs).

**Comment by CloudyPadmal** [comment]
Same content means code. `USBReceiver` class is present in both. Btw how many USB reading classes we have?

**Comment by jddeep** [comment]
> Same content means code. `USBReceiver` class is present in both. Btw how many USB reading classes we have?

@CloudyPadmal Yes, I had to include the `USBReceiver` class to make changes for this PR. Functions related to read and work with the data are there in this class only. This class is not exactly related to USB but infact for the detected Arduino device. Might we rename this class to something like `DataReceiver`?

**Comment by CloudyPadmal** [comment]
Yes probably. I dunno there seems to be a lot of redundant and duplicate code in app. Seems like there's no proper architecture. Have to revise the whole code. Will do in a couple of days.

**Comment by CloudyPadmal** [comment]
Conflicts

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
