### PR TITLE
Import Data Feature in Focus Mode

### LINKED ISSUE #301: Data from datasets/Arduino in Focus Mode Animation
**Actual Behaviour.**  
Missing Data from datasets/Arduino in Focus Mode Animation.

**Expected Behaviour**  
Data from datasets/Arduino in Focus Mode to implement Animation.

**Additional context**  
> Not available

**Would you like to work on the issue?**
Issue for GSOC 2019

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #301 

**Changes**: Import Data Feature in Focus Mode.

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/neurolab-android/files/3357682/app-debug.zip)

### CODE REVIEW

**Comment by mariobehling** [comment]
We cannot see that this is actually playing back a saved data. Please implement:
a) Play, Stop, Record buttons
b) Import the data to the data logger itself. Then it can be played back from the datalogger just like in PSLab. Please follow PSLab's implementation!

**Review by mariobehling — CHANGES_REQUESTED** [review]
The data should be imported into the datalogger, not into the rocket game directly!

**Comment by jddeep** [comment]
Done.

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
Ok, merging this as WIP.

**Pull request merged**
