### PR TITLE
Updated Navigation Drawer and logo

### LINKED ISSUE #278: nav drawer logo image needs an update
**Actual Behaviour.**  
* The current image type is not a vector graphic.
* The app logo on the nav drawer doesn't match with the current theme of the app as it was designed taking into the account the previous theme.

**Expected Behaviour**  
* A matching (with the app theme) vector graphic logo in the navigation drawer.

**Steps to reproduce it**  
* Open the app.
* Open the nav drawer and look at the logo at the top.

**Screenshot of the current nav drawer logo**:

**Would you like to work on the issue?**
@ho-dor @jddeep

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #278 

**Changes**: Updated Navigation Drawer and logo

Co-authored-by: Aditya Gupta adityastic@users.noreply.github.com

**Screenshot/s for the changes**: 
navdrawerupdate(1)

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by jddeep** [comment]
Logo design credit : @adityastic :D

**Comment by adityastic** [comment]
@jddeep you can co author me xD.
By Adding: 
<EmptyLine>
Co-authored-by: Aditya Gupta <adityastic@users.noreply.github.com>

to the commit message xD. Your Welcome

**Comment by adityastic** [comment]
@jddeep you can co author me xD.
By Adding: 
//newLine//
Co-authored-by: Aditya Gupta \<adityastic@users.noreply.github.com\>

to the commit message xD. Your Welcome

**Comment by jddeep** [comment]
> 
> 
> @jddeep you can co author me xD.
> By Adding:
> //newLine//
> Co-authored-by: Aditya Gupta <[adityastic@users.noreply.github.com](mailto:adityastic@users.noreply.github.com)>
> 
> to the commit message xD. Your Welcome

Alright man. No issues.

**Comment by adityastic** [comment]
@jddeep you can co author me xD.



> > @jddeep you can co author me xD.
> > By Adding:
> > //newLine//
> > Co-authored-by: Aditya Gupta <[adityastic@users.noreply.github.com](mailto:adityastic@users.noreply.github.com)>
> > to the commit message xD. Your Welcome
> 
> Alright man. No issues.

Thanks xD

**Review by CloudyPadmal — APPROVED** [review]

**Review by suresh-gandhi — APPROVED** [review]

**Pull request merged**
